# Generated by Django 5.0.7 on 2024-08-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile_pic',
            field=models.ImageField(default=False, upload_to='posts/users/'),
        ),
    ]
