# Generated by Django 5.0.7 on 2024-08-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_profile_pic_comment_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
