# Generated by Django 5.0.7 on 2024-10-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_to_read',
            field=models.CharField(max_length=500),
        ),
    ]
